### ISSUE TITLE
Powerwall 20.49.0 no longer working

### ISSUE THREAD

**Issue by dantran99** [datMaffin/homebridge-tesla-powerwall#23] opened 2021-02-24 05:20 UTC
Hi, software update 20.49.0 broke the communication with the powerwall. From reading through the API GitHub, some features now require authentication.

**Comment by datMaffin** [comment] 2021-02-24 21:00
Thanks for reporting this issue!

I will close this issue, however, as it is a duplicate of #21.

**Closed by datMaffin** 2021-02-24 21:00 UTC
