### ISSUE TITLE
Homebridge warnings from powerwall2

### ISSUE THREAD

**Issue by OrigSorceror** [datMaffin/homebridge-tesla-powerwall#24] opened 2021-03-25 12:17 UTC
keep getting these warnings in loges for Homebridge. 
[25/03/2021, 10:46:26 pm] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[25/03/2021, 10:46:26 pm] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[25/03/2021, 10:46:27 pm] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[25/03/2021, 10:46:27 pm] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[25/03/2021, 10:46:27 pm] [homebridge-tesla-powerwall] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by datMaffin** [comment] 2021-03-25 12:25
Thanks for reporting this issue!
However, this is a duplicate of #22

**Closed by datMaffin** 2021-03-25 12:25 UTC
